export const TITLE_MAPPINGS: Record<string, string> = {
    "resilientdb.pdf": "ResilientDB: Global Scale Resilient Blockchain Fabric",
    "rcc.pdf":
      "Resilient Concurrent Consensus for High-Throughput Secure Transaction Processing",
    "bchain-transaction-pro.pdf": "Blockchain Transaction Processing",
  };

  export const DEFAULT_IMPLEMENTATION_KEYWORDS = [
    "function",
    "method",
    "class",
    "struct",
    "implementation",
    "code",
    "example",
    "snippet",
    "solution",
    "procedure",
    "algorithm implementation",
    "working code",
    "complete implementation",
    "full implementation",
    "source code",
    "programming",
    "coding",
    "execute",
    "run",
    "compile",
    "build",
    "deploy",
    "test",
    "debug",
    "return",
    "if",
    "else",
    "for",
    "while",
    "loop",
    "iterate",
    "variable",
    "parameter",
    "argument",
    "constructor",
    "destructor",
    "getter",
    "setter",
    "property",
    "attribute",
    "field",
    "member"
  ];
  
  // keywords that indicate theoretical or academic content (still valuable but lower priority)
  export const DEFAULT_THEORETICAL_KEYWORDS = [
    "algorithm",
    "proof",
    "theorem",
    "lemma",
    "complexity",
    "time complexity",
    "space complexity",
    "big o",
    "optimization",
    "analysis",
    "theoretical",
    "mathematical",
    "formal verification",
    "correctness",
    "invariant",
    "precondition",
    "postcondition",
    "specification",
    "model",
    "framework",
    "architecture",
    "design pattern",
    "abstract",
    "conceptual"
  ];
  
  // indicators of implementation quality and completeness
  export const DEFAULT_QUALITY_INDICATORS = [
    "complete",
    "full",
    "working",
    "tested",
    "functional",
    "operational",
    "ready",
    "finished",
    "implemented",
    "error handling",
    "exception handling",
    "validation",
    "robust",
    "production",
    "stable",
    "reliable",
    "efficient",
    "optimized",
    "refactored",
    "clean code",
    "best practice",
    "documentation",
    "comments",
    "unit test",
    "integration test",
    "example usage",
    "demo",
    "tutorial"
  ];