name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Make INSTALL.sh executable
      run: chmod +x INSTALL.sh

    - name: Run INSTALL script
      run: ./INSTALL.sh

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install npm dependencies
      run: npm install

    - name: Start GraphQL server
      run: npm start &
      env:
        NODE_ENV: test

    - name: Wait for GraphQL server to be ready
      run: sleep 10

    - name: Run tests
      run: npm test
