header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Apache Software Foundation

  paths-ignore:
    - '.*'
    - '.**/**'
    - 'CNAME'
    - '**/*.conf'
    - '**/*.config'
    - '**/*.json'
    - '**/*.sol'
    - '**/*.pri'
    - '**/*.pub'
    - 'dev/.rat-excludes'
    - 'DISCLAIMER'
    - 'NOTICE'
    - 'LICENSE'
    - 'documents/doxygen/.gitignore'
    - 'third_party/loc_script/src/index.js'



  comment: on-failure

