header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Apache Software Foundation

  paths-ignore:
    - '.*'
    - '.**/*'
    - "ecosystem/**/.*"
    - '**/*.sol'
    - CNAME
    - DISCLAIMER
    - LICENSE
    - NOTICE
    - 'dev/.rat-excludes'
    - 'documents/doxygen/.gitignore'
    - 'third_party/loc_script/src/index.js'
    - '**/*.json'
    - '**/*.config'
    - '**/*.conf'



  comment: on-failure

