header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Apache Software Foundation

  paths-ignore:
    - '.*'
    - '.**/**'
    - '**/*.sol'
    - '**/*.config'
    - '**/*.conf'
    - '**/*.json'
    - '**/*.prettierrc'
    - CNAME
    - DISCLAIMER
    - LICENSE
    - NOTICE
    - 'dev/.rat-excludes'
    - 'documents/doxygen/.gitignore'
    - 'third_party/loc_script/src/index.js'
    # Ecosystem-specific exclusions & Fille types which do not support headers (like JSON, etc.)
    - 'ecosystem/**/.rat-excludes'
    - 'ecosystem/**/.gitignore'
    - 'ecosystem/**/.bazelrc'
    - 'ecosystem/**/.gitattributes'
    - 'ecosystem/**/.npmrc'
    - 'ecosystem/**/.prettierrc'
    - 'ecosystem/**/.prettierignore'
    - 'ecosystem/**/.licenserc.yaml'
    - 'ecosystem/**/*.json'
    - 'ecosystem/**/.nvmrc'
    - 'ecosystem/**/.env*'
    - 'ecosystem/**/*.svg'
    - 'ecosystem/**/next-env.d.ts'
    - 'ecosystem/**/.vscode/**'
    # Beacon content MDX files don't support license headers
    - 'ecosystem/AI-Tooling/beacon/content/**'
    # Pocketflow is MIT-licensed third-party code
    - 'ecosystem/pocketflow/**'

  comment: on-failure

