header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Apache Software Foundation

  paths-ignore:
    - '.*'
    - '.**/**'
    - '**/*.sol'
    - CNAME
    - DISCLAIMER
    - LICENSE
    - NOTICE
    - 'dev/.rat-excludes'
    - 'documents/doxygen/.gitignore'
    - 'third_party/loc_script/src/index.js'
    - 'ecosystem/**/*.mdx'
    - 'ecosystem/**/*.json'
    # Pocketflow is MIT-licensed third-party code
    - 'ecosystem/pocketflow/**'


  comment: on-failure
