var annotated_dup =
[
    [ "resdb", "namespaceresdb.html", [
      [ "contract", "namespaceresdb_1_1contract.html", [
        [ "AddressManager", "classresdb_1_1contract_1_1AddressManager.html", "classresdb_1_1contract_1_1AddressManager" ],
        [ "ContractClient", "classresdb_1_1contract_1_1ContractClient.html", "classresdb_1_1contract_1_1ContractClient" ],
        [ "ContractExecutor", "classresdb_1_1contract_1_1ContractExecutor.html", "classresdb_1_1contract_1_1ContractExecutor" ],
        [ "ContractManager", "classresdb_1_1contract_1_1ContractManager.html", "classresdb_1_1contract_1_1ContractManager" ]
      ] ],
      [ "AsyncAcceptor", "classresdb_1_1AsyncAcceptor.html", "classresdb_1_1AsyncAcceptor" ],
      [ "AsyncReplicaClient", "classresdb_1_1AsyncReplicaClient.html", "classresdb_1_1AsyncReplicaClient" ],
      [ "AtomicUniquePtr", "classresdb_1_1AtomicUniquePtr.html", "classresdb_1_1AtomicUniquePtr" ],
      [ "BatchQueue", "classresdb_1_1BatchQueue.html", "classresdb_1_1BatchQueue" ],
      [ "BlockingQueue", "classresdb_1_1BlockingQueue.html", "classresdb_1_1BlockingQueue" ],
      [ "CheckPointManager", "classresdb_1_1CheckPointManager.html", "classresdb_1_1CheckPointManager" ],
      [ "Commitment", "classresdb_1_1Commitment.html", "classresdb_1_1Commitment" ],
      [ "ConsensusService", "classresdb_1_1ConsensusService.html", "classresdb_1_1ConsensusService" ],
      [ "ConsensusServiceGeoPBFT", "classresdb_1_1ConsensusServiceGeoPBFT.html", "classresdb_1_1ConsensusServiceGeoPBFT" ],
      [ "ConsensusServicePBFT", "classresdb_1_1ConsensusServicePBFT.html", "classresdb_1_1ConsensusServicePBFT" ],
      [ "Context", "structresdb_1_1Context.html", "structresdb_1_1Context" ],
      [ "CrowService", "classresdb_1_1CrowService.html", "classresdb_1_1CrowService" ],
      [ "DataInfo", "structresdb_1_1DataInfo.html", "structresdb_1_1DataInfo" ],
      [ "GeoGlobalExecutor", "classresdb_1_1GeoGlobalExecutor.html", "classresdb_1_1GeoGlobalExecutor" ],
      [ "GeoPBFTClient", "classresdb_1_1GeoPBFTClient.html", "classresdb_1_1GeoPBFTClient" ],
      [ "GeoPBFTCommitment", "classresdb_1_1GeoPBFTCommitment.html", "classresdb_1_1GeoPBFTCommitment" ],
      [ "GeoPBFTExecutorImpl", "classresdb_1_1GeoPBFTExecutorImpl.html", "classresdb_1_1GeoPBFTExecutorImpl" ],
      [ "GeoTransactionExecutor", "classresdb_1_1GeoTransactionExecutor.html", "classresdb_1_1GeoTransactionExecutor" ],
      [ "KeyGenerator", "classresdb_1_1KeyGenerator.html", null ],
      [ "KVServerExecutor", "classresdb_1_1KVServerExecutor.html", "classresdb_1_1KVServerExecutor" ],
      [ "LockFreeCollectorPool", "classresdb_1_1LockFreeCollectorPool.html", "classresdb_1_1LockFreeCollectorPool" ],
      [ "LockFreeQueue", "classresdb_1_1LockFreeQueue.html", "classresdb_1_1LockFreeQueue" ],
      [ "Logging", "classresdb_1_1Logging.html", "classresdb_1_1Logging" ],
      [ "MockAsyncReplicaClient", "classresdb_1_1MockAsyncReplicaClient.html", "classresdb_1_1MockAsyncReplicaClient" ],
      [ "MockCheckPointManager", "classresdb_1_1MockCheckPointManager.html", "classresdb_1_1MockCheckPointManager" ],
      [ "MockGeoGlobalExecutor", "classresdb_1_1MockGeoGlobalExecutor.html", "classresdb_1_1MockGeoGlobalExecutor" ],
      [ "MockResDBClient", "classresdb_1_1MockResDBClient.html", "classresdb_1_1MockResDBClient" ],
      [ "MockResDBReplicaClient", "classresdb_1_1MockResDBReplicaClient.html", "classresdb_1_1MockResDBReplicaClient" ],
      [ "MockResDBService", "classresdb_1_1MockResDBService.html", "classresdb_1_1MockResDBService" ],
      [ "MockResDBTxnClient", "classresdb_1_1MockResDBTxnClient.html", "classresdb_1_1MockResDBTxnClient" ],
      [ "MockSignatureVerifier", "classresdb_1_1MockSignatureVerifier.html", "classresdb_1_1MockSignatureVerifier" ],
      [ "MockSocket", "classresdb_1_1MockSocket.html", "classresdb_1_1MockSocket" ],
      [ "MockTransactionExecutorDataImpl", "classresdb_1_1MockTransactionExecutorDataImpl.html", "classresdb_1_1MockTransactionExecutorDataImpl" ],
      [ "MockTransactionExecutorImpl", "classresdb_1_1MockTransactionExecutorImpl.html", "classresdb_1_1MockTransactionExecutorImpl" ],
      [ "PerformanceManager", "classresdb_1_1PerformanceManager.html", "classresdb_1_1PerformanceManager" ],
      [ "PrometheusHandler", "classresdb_1_1PrometheusHandler.html", "classresdb_1_1PrometheusHandler" ],
      [ "PYVerificator", "classresdb_1_1PYVerificator.html", "classresdb_1_1PYVerificator" ],
      [ "Query", "classresdb_1_1Query.html", "classresdb_1_1Query" ],
      [ "QueueItem", "structresdb_1_1QueueItem.html", "structresdb_1_1QueueItem" ],
      [ "RequestInfo", "structresdb_1_1RequestInfo.html", "structresdb_1_1RequestInfo" ],
      [ "ResDBClient", "classresdb_1_1ResDBClient.html", "classresdb_1_1ResDBClient" ],
      [ "ResDBConfig", "classresdb_1_1ResDBConfig.html", "classresdb_1_1ResDBConfig" ],
      [ "ResDBKVClient", "classresdb_1_1ResDBKVClient.html", "classresdb_1_1ResDBKVClient" ],
      [ "ResDBKVPerformanceClient", "classresdb_1_1ResDBKVPerformanceClient.html", "classresdb_1_1ResDBKVPerformanceClient" ],
      [ "ResDBReplicaClient", "classresdb_1_1ResDBReplicaClient.html", "classresdb_1_1ResDBReplicaClient" ],
      [ "ResDBServer", "classresdb_1_1ResDBServer.html", "classresdb_1_1ResDBServer" ],
      [ "ResDBService", "classresdb_1_1ResDBService.html", "classresdb_1_1ResDBService" ],
      [ "ResDBStateClient", "classresdb_1_1ResDBStateClient.html", "classresdb_1_1ResDBStateClient" ],
      [ "ResDBTest", "classresdb_1_1ResDBTest.html", "classresdb_1_1ResDBTest" ],
      [ "ResDBTestClient", "classresdb_1_1ResDBTestClient.html", "classresdb_1_1ResDBTestClient" ],
      [ "ResDBTestExecutor", "classresdb_1_1ResDBTestExecutor.html", "classresdb_1_1ResDBTestExecutor" ],
      [ "ResDBTxnClient", "classresdb_1_1ResDBTxnClient.html", "classresdb_1_1ResDBTxnClient" ],
      [ "ResDBUserClient", "classresdb_1_1ResDBUserClient.html", "classresdb_1_1ResDBUserClient" ],
      [ "ResponseManager", "classresdb_1_1ResponseManager.html", "classresdb_1_1ResponseManager" ],
      [ "SDKTransaction", "structresdb_1_1SDKTransaction.html", "structresdb_1_1SDKTransaction" ],
      [ "ServerFactory", "classresdb_1_1ServerFactory.html", "classresdb_1_1ServerFactory" ],
      [ "SignatureVerifier", "classresdb_1_1SignatureVerifier.html", "classresdb_1_1SignatureVerifier" ],
      [ "Socket", "classresdb_1_1Socket.html", "classresdb_1_1Socket" ],
      [ "SpinLockSet", "classresdb_1_1SpinLockSet.html", "classresdb_1_1SpinLockSet" ],
      [ "Stats", "classresdb_1_1Stats.html", "classresdb_1_1Stats" ],
      [ "SystemInfo", "classresdb_1_1SystemInfo.html", "classresdb_1_1SystemInfo" ],
      [ "TcpSocket", "classresdb_1_1TcpSocket.html", "classresdb_1_1TcpSocket" ],
      [ "TransactionCollector", "classresdb_1_1TransactionCollector.html", "classresdb_1_1TransactionCollector" ],
      [ "TransactionExecutor", "classresdb_1_1TransactionExecutor.html", "classresdb_1_1TransactionExecutor" ],
      [ "TransactionExecutorImpl", "classresdb_1_1TransactionExecutorImpl.html", "classresdb_1_1TransactionExecutorImpl" ],
      [ "TransactionManager", "classresdb_1_1TransactionManager.html", "classresdb_1_1TransactionManager" ],
      [ "TxnMemoryDB", "classresdb_1_1TxnMemoryDB.html", "classresdb_1_1TxnMemoryDB" ],
      [ "ViewChangeManager", "classresdb_1_1ViewChangeManager.html", "classresdb_1_1ViewChangeManager" ]
    ] ],
    [ "resdb_validator", "namespaceresdb__validator.html", [
      [ "exceptions", "namespaceresdb__validator_1_1exceptions.html", [
        [ "AmountError", "classresdb__validator_1_1exceptions_1_1AmountError.html", null ],
        [ "AssetIdMismatch", "classresdb__validator_1_1exceptions_1_1AssetIdMismatch.html", null ],
        [ "ConfigurationError", "classresdb__validator_1_1exceptions_1_1ConfigurationError.html", null ],
        [ "CyclicBlockchainError", "classresdb__validator_1_1exceptions_1_1CyclicBlockchainError.html", null ],
        [ "DatabaseDoesNotExist", "classresdb__validator_1_1exceptions_1_1DatabaseDoesNotExist.html", null ],
        [ "DoubleSpend", "classresdb__validator_1_1exceptions_1_1DoubleSpend.html", null ],
        [ "DuplicateTransaction", "classresdb__validator_1_1exceptions_1_1DuplicateTransaction.html", null ],
        [ "InputDoesNotExist", "classresdb__validator_1_1exceptions_1_1InputDoesNotExist.html", null ],
        [ "InvalidHash", "classresdb__validator_1_1exceptions_1_1InvalidHash.html", null ],
        [ "InvalidPowerChange", "classresdb__validator_1_1exceptions_1_1InvalidPowerChange.html", null ],
        [ "InvalidProposer", "classresdb__validator_1_1exceptions_1_1InvalidProposer.html", null ],
        [ "InvalidPublicKey", "classresdb__validator_1_1exceptions_1_1InvalidPublicKey.html", null ],
        [ "InvalidSignature", "classresdb__validator_1_1exceptions_1_1InvalidSignature.html", null ],
        [ "KeypairMismatchException", "classresdb__validator_1_1exceptions_1_1KeypairMismatchException.html", null ],
        [ "MultipleInputsError", "classresdb__validator_1_1exceptions_1_1MultipleInputsError.html", null ],
        [ "MultipleValidatorOperationError", "classresdb__validator_1_1exceptions_1_1MultipleValidatorOperationError.html", null ],
        [ "OperationError", "classresdb__validator_1_1exceptions_1_1OperationError.html", null ],
        [ "ResDBError", "classresdb__validator_1_1exceptions_1_1ResDBError.html", null ],
        [ "SchemaValidationError", "classresdb__validator_1_1exceptions_1_1SchemaValidationError.html", null ],
        [ "StartupError", "classresdb__validator_1_1exceptions_1_1StartupError.html", null ],
        [ "ThresholdTooDeep", "classresdb__validator_1_1exceptions_1_1ThresholdTooDeep.html", null ],
        [ "TransactionOwnerError", "classresdb__validator_1_1exceptions_1_1TransactionOwnerError.html", null ],
        [ "UnequalValidatorSet", "classresdb__validator_1_1exceptions_1_1UnequalValidatorSet.html", null ],
        [ "ValidationError", "classresdb__validator_1_1exceptions_1_1ValidationError.html", null ]
      ] ],
      [ "lib", "namespaceresdb__validator_1_1lib.html", [
        [ "ResDB", "classresdb__validator_1_1lib_1_1ResDB.html", "classresdb__validator_1_1lib_1_1ResDB" ]
      ] ],
      [ "memoize", "namespaceresdb__validator_1_1memoize.html", [
        [ "HDict", "classresdb__validator_1_1memoize_1_1HDict.html", "classresdb__validator_1_1memoize_1_1HDict" ],
        [ "ToDictWrapper", "classresdb__validator_1_1memoize_1_1ToDictWrapper.html", "classresdb__validator_1_1memoize_1_1ToDictWrapper" ]
      ] ],
      [ "models", "namespaceresdb__validator_1_1models.html", [
        [ "FastTransaction", "classresdb__validator_1_1models_1_1FastTransaction.html", "classresdb__validator_1_1models_1_1FastTransaction" ],
        [ "Transaction", "classresdb__validator_1_1models_1_1Transaction.html", "classresdb__validator_1_1models_1_1Transaction" ]
      ] ],
      [ "transaction", "namespaceresdb__validator_1_1transaction.html", [
        [ "Input", "classresdb__validator_1_1transaction_1_1Input.html", "classresdb__validator_1_1transaction_1_1Input" ],
        [ "Output", "classresdb__validator_1_1transaction_1_1Output.html", "classresdb__validator_1_1transaction_1_1Output" ],
        [ "Transaction", "classresdb__validator_1_1transaction_1_1Transaction.html", "classresdb__validator_1_1transaction_1_1Transaction" ],
        [ "TransactionLink", "classresdb__validator_1_1transaction_1_1TransactionLink.html", "classresdb__validator_1_1transaction_1_1TransactionLink" ]
      ] ]
    ] ],
    [ "LevelDurable", "classLevelDurable.html", "classLevelDurable" ],
    [ "RocksDurable", "classRocksDurable.html", "classRocksDurable" ]
];