var annotated_dup =
[
    [ "resdb", "d5/d10/namespaceresdb.html", [
      [ "contract", "d8/d28/namespaceresdb_1_1contract.html", [
        [ "AddressManager", "d4/d26/classresdb_1_1contract_1_1AddressManager.html", "d4/d26/classresdb_1_1contract_1_1AddressManager" ],
        [ "ContractClient", "d9/dfa/classresdb_1_1contract_1_1ContractClient.html", "d9/dfa/classresdb_1_1contract_1_1ContractClient" ],
        [ "ContractManager", "d6/d7d/classresdb_1_1contract_1_1ContractManager.html", "d6/d7d/classresdb_1_1contract_1_1ContractManager" ],
        [ "ContractTransactionManager", "d7/d96/classresdb_1_1contract_1_1ContractTransactionManager.html", "d7/d96/classresdb_1_1contract_1_1ContractTransactionManager" ]
      ] ],
      [ "storage", "dd/dae/namespaceresdb_1_1storage.html", [
        [ "MemoryDB", "da/d75/classresdb_1_1storage_1_1MemoryDB.html", "da/d75/classresdb_1_1storage_1_1MemoryDB" ],
        [ "ResLevelDB", "d3/d39/classresdb_1_1storage_1_1ResLevelDB.html", "d3/d39/classresdb_1_1storage_1_1ResLevelDB" ],
        [ "ResRocksDB", "d9/d1d/classresdb_1_1storage_1_1ResRocksDB.html", "d9/d1d/classresdb_1_1storage_1_1ResRocksDB" ]
      ] ],
      [ "utxo", "d1/d74/namespaceresdb_1_1utxo.html", [
        [ "QueryExecutor", "d0/da0/classresdb_1_1utxo_1_1QueryExecutor.html", "d0/da0/classresdb_1_1utxo_1_1QueryExecutor" ],
        [ "Transaction", "d8/d15/classresdb_1_1utxo_1_1Transaction.html", "d8/d15/classresdb_1_1utxo_1_1Transaction" ],
        [ "TxMempool", "d7/d32/classresdb_1_1utxo_1_1TxMempool.html", "d7/d32/classresdb_1_1utxo_1_1TxMempool" ],
        [ "UTXOClient", "d0/dfe/classresdb_1_1utxo_1_1UTXOClient.html", "d0/dfe/classresdb_1_1utxo_1_1UTXOClient" ],
        [ "UTXOExecutor", "de/de8/classresdb_1_1utxo_1_1UTXOExecutor.html", "de/de8/classresdb_1_1utxo_1_1UTXOExecutor" ],
        [ "Wallet", "df/ddc/classresdb_1_1utxo_1_1Wallet.html", "df/ddc/classresdb_1_1utxo_1_1Wallet" ]
      ] ],
      [ "Acceptor", "d6/dac/classresdb_1_1Acceptor.html", "d6/dac/classresdb_1_1Acceptor" ],
      [ "AsyncAcceptor", "d3/d77/classresdb_1_1AsyncAcceptor.html", "d3/d77/classresdb_1_1AsyncAcceptor" ],
      [ "AsyncReplicaClient", "d8/d9d/classresdb_1_1AsyncReplicaClient.html", "d8/d9d/classresdb_1_1AsyncReplicaClient" ],
      [ "AtomicUniquePtr", "db/d71/classresdb_1_1AtomicUniquePtr.html", "db/d71/classresdb_1_1AtomicUniquePtr" ],
      [ "BatchQueue", "d5/db6/classresdb_1_1BatchQueue.html", "d5/db6/classresdb_1_1BatchQueue" ],
      [ "BlockingQueue", "dd/d88/classresdb_1_1BlockingQueue.html", "dd/d88/classresdb_1_1BlockingQueue" ],
      [ "ChainState", "d8/d22/classresdb_1_1ChainState.html", "d8/d22/classresdb_1_1ChainState" ],
      [ "CheckPoint", "d2/dce/classresdb_1_1CheckPoint.html", "d2/dce/classresdb_1_1CheckPoint" ],
      [ "CheckPointManager", "dc/db0/classresdb_1_1CheckPointManager.html", "dc/db0/classresdb_1_1CheckPointManager" ],
      [ "Commitment", "dd/d4b/classresdb_1_1Commitment.html", "dd/d4b/classresdb_1_1Commitment" ],
      [ "ComplaningClients", "d3/da3/classresdb_1_1ComplaningClients.html", "d3/da3/classresdb_1_1ComplaningClients" ],
      [ "ConsensusManager", "da/d19/classresdb_1_1ConsensusManager.html", "da/d19/classresdb_1_1ConsensusManager" ],
      [ "ConsensusManagerGeoPBFT", "dd/dea/classresdb_1_1ConsensusManagerGeoPBFT.html", "dd/dea/classresdb_1_1ConsensusManagerGeoPBFT" ],
      [ "ConsensusManagerPBFT", "d0/ded/classresdb_1_1ConsensusManagerPBFT.html", "d0/ded/classresdb_1_1ConsensusManagerPBFT" ],
      [ "Context", "d8/d18/structresdb_1_1Context.html", "d8/d18/structresdb_1_1Context" ],
      [ "CustomQuery", "d6/dd9/classresdb_1_1CustomQuery.html", "d6/dd9/classresdb_1_1CustomQuery" ],
      [ "DataInfo", "dd/dd6/structresdb_1_1DataInfo.html", "dd/dd6/structresdb_1_1DataInfo" ],
      [ "DuplicateManager", "d6/da0/classresdb_1_1DuplicateManager.html", "d6/da0/classresdb_1_1DuplicateManager" ],
      [ "GeoGlobalExecutor", "d4/d2d/classresdb_1_1GeoGlobalExecutor.html", "d4/d2d/classresdb_1_1GeoGlobalExecutor" ],
      [ "GeoPBFTCommitment", "df/d2b/classresdb_1_1GeoPBFTCommitment.html", "df/d2b/classresdb_1_1GeoPBFTCommitment" ],
      [ "GeoTransactionExecutor", "d9/d92/classresdb_1_1GeoTransactionExecutor.html", "d9/d92/classresdb_1_1GeoTransactionExecutor" ],
      [ "KeyGenerator", "d5/d5c/classresdb_1_1KeyGenerator.html", null ],
      [ "KVClient", "d4/dbb/classresdb_1_1KVClient.html", "d4/dbb/classresdb_1_1KVClient" ],
      [ "KVExecutor", "d3/d37/classresdb_1_1KVExecutor.html", "d3/d37/classresdb_1_1KVExecutor" ],
      [ "LockFreeCollectorPool", "d7/d31/classresdb_1_1LockFreeCollectorPool.html", "d7/d31/classresdb_1_1LockFreeCollectorPool" ],
      [ "LockFreeQueue", "da/dd3/classresdb_1_1LockFreeQueue.html", "da/dd3/classresdb_1_1LockFreeQueue" ],
      [ "MessageManager", "d7/d18/classresdb_1_1MessageManager.html", "d7/d18/classresdb_1_1MessageManager" ],
      [ "MockAsyncReplicaClient", "d8/d4f/classresdb_1_1MockAsyncReplicaClient.html", "d8/d4f/classresdb_1_1MockAsyncReplicaClient" ],
      [ "MockCheckPoint", "d8/dcb/classresdb_1_1MockCheckPoint.html", "d8/dcb/classresdb_1_1MockCheckPoint" ],
      [ "MockCheckPointManager", "de/da4/classresdb_1_1MockCheckPointManager.html", "de/da4/classresdb_1_1MockCheckPointManager" ],
      [ "MockGeoGlobalExecutor", "d7/ddc/classresdb_1_1MockGeoGlobalExecutor.html", "d7/ddc/classresdb_1_1MockGeoGlobalExecutor" ],
      [ "MockNetChannel", "d4/dac/classresdb_1_1MockNetChannel.html", "d4/dac/classresdb_1_1MockNetChannel" ],
      [ "MockReplicaCommunicator", "d4/de4/classresdb_1_1MockReplicaCommunicator.html", "d4/de4/classresdb_1_1MockReplicaCommunicator" ],
      [ "MockResDBTxnAccessor", "d0/d8d/classresdb_1_1MockResDBTxnAccessor.html", "d0/d8d/classresdb_1_1MockResDBTxnAccessor" ],
      [ "MockServiceInterface", "d8/da4/classresdb_1_1MockServiceInterface.html", "d8/da4/classresdb_1_1MockServiceInterface" ],
      [ "MockSignatureVerifier", "de/d05/classresdb_1_1MockSignatureVerifier.html", "de/d05/classresdb_1_1MockSignatureVerifier" ],
      [ "MockSocket", "dd/dd7/classresdb_1_1MockSocket.html", "dd/dd7/classresdb_1_1MockSocket" ],
      [ "MockStorage", "de/d28/classresdb_1_1MockStorage.html", "de/d28/classresdb_1_1MockStorage" ],
      [ "MockTransactionExecutorDataImpl", "dc/db6/classresdb_1_1MockTransactionExecutorDataImpl.html", "dc/db6/classresdb_1_1MockTransactionExecutorDataImpl" ],
      [ "MockTransactionManager", "dc/d6d/classresdb_1_1MockTransactionManager.html", "dc/d6d/classresdb_1_1MockTransactionManager" ],
      [ "NetChannel", "de/dc3/classresdb_1_1NetChannel.html", "de/dc3/classresdb_1_1NetChannel" ],
      [ "PerformanceClientTimeout", "d7/dbd/classresdb_1_1PerformanceClientTimeout.html", "d7/dbd/classresdb_1_1PerformanceClientTimeout" ],
      [ "PerformanceManager", "d1/d89/classresdb_1_1PerformanceManager.html", "d1/d89/classresdb_1_1PerformanceManager" ],
      [ "PreVerifyConsensusServicePBFT", "da/d52/classresdb_1_1PreVerifyConsensusServicePBFT.html", "da/d52/classresdb_1_1PreVerifyConsensusServicePBFT" ],
      [ "PrometheusHandler", "df/dcf/classresdb_1_1PrometheusHandler.html", "df/dcf/classresdb_1_1PrometheusHandler" ],
      [ "Query", "de/d6d/classresdb_1_1Query.html", "de/d6d/classresdb_1_1Query" ],
      [ "QueueItem", "df/d64/structresdb_1_1QueueItem.html", "df/d64/structresdb_1_1QueueItem" ],
      [ "Recovery", "d1/d44/classresdb_1_1Recovery.html", "d1/d44/classresdb_1_1Recovery" ],
      [ "ReplicaCommunicator", "d3/d5e/classresdb_1_1ReplicaCommunicator.html", "d3/d5e/classresdb_1_1ReplicaCommunicator" ],
      [ "RequestInfo", "d8/d15/structresdb_1_1RequestInfo.html", "d8/d15/structresdb_1_1RequestInfo" ],
      [ "ResDBConfig", "db/ddb/classresdb_1_1ResDBConfig.html", "db/ddb/classresdb_1_1ResDBConfig" ],
      [ "ResDBPoCConfig", "da/d86/classresdb_1_1ResDBPoCConfig.html", "da/d86/classresdb_1_1ResDBPoCConfig" ],
      [ "ResDBStateAccessor", "d7/d30/classresdb_1_1ResDBStateAccessor.html", "d7/d30/classresdb_1_1ResDBStateAccessor" ],
      [ "ResDBTest", "dd/d33/classresdb_1_1ResDBTest.html", "dd/d33/classresdb_1_1ResDBTest" ],
      [ "ResDBTestClient", "d8/d65/classresdb_1_1ResDBTestClient.html", "d8/d65/classresdb_1_1ResDBTestClient" ],
      [ "ResDBTestManager", "d0/d2a/classresdb_1_1ResDBTestManager.html", "d0/d2a/classresdb_1_1ResDBTestManager" ],
      [ "ResDBTxnAccessor", "da/d12/classresdb_1_1ResDBTxnAccessor.html", "da/d12/classresdb_1_1ResDBTxnAccessor" ],
      [ "ResponseManager", "da/d2f/classresdb_1_1ResponseManager.html", "da/d2f/classresdb_1_1ResponseManager" ],
      [ "ServerFactory", "da/d3b/classresdb_1_1ServerFactory.html", "da/d3b/classresdb_1_1ServerFactory" ],
      [ "ServiceInterface", "da/d3b/classresdb_1_1ServiceInterface.html", "da/d3b/classresdb_1_1ServiceInterface" ],
      [ "ServiceNetwork", "d4/d2d/classresdb_1_1ServiceNetwork.html", "d4/d2d/classresdb_1_1ServiceNetwork" ],
      [ "SignatureVerifier", "d4/d30/classresdb_1_1SignatureVerifier.html", "d4/d30/classresdb_1_1SignatureVerifier" ],
      [ "SignatureVerifierInterface", "de/d77/classresdb_1_1SignatureVerifierInterface.html", "de/d77/classresdb_1_1SignatureVerifierInterface" ],
      [ "Socket", "d0/d29/classresdb_1_1Socket.html", "d0/d29/classresdb_1_1Socket" ],
      [ "SpinLockSet", "d4/d35/classresdb_1_1SpinLockSet.html", "d4/d35/classresdb_1_1SpinLockSet" ],
      [ "Stats", "de/d0d/classresdb_1_1Stats.html", "de/d0d/classresdb_1_1Stats" ],
      [ "Storage", "d2/d14/classresdb_1_1Storage.html", "d2/d14/classresdb_1_1Storage" ],
      [ "SystemInfo", "d9/d27/classresdb_1_1SystemInfo.html", "d9/d27/classresdb_1_1SystemInfo" ],
      [ "TcpSocket", "d4/de5/classresdb_1_1TcpSocket.html", "d4/de5/classresdb_1_1TcpSocket" ],
      [ "TransactionCollector", "d7/d95/classresdb_1_1TransactionCollector.html", "d7/d95/classresdb_1_1TransactionCollector" ],
      [ "TransactionConstructor", "d0/da5/classresdb_1_1TransactionConstructor.html", "d0/da5/classresdb_1_1TransactionConstructor" ],
      [ "TransactionExecutor", "da/dfa/classresdb_1_1TransactionExecutor.html", "da/dfa/classresdb_1_1TransactionExecutor" ],
      [ "TransactionManager", "df/d01/classresdb_1_1TransactionManager.html", "df/d01/classresdb_1_1TransactionManager" ],
      [ "ViewChangeManager", "d1/db2/classresdb_1_1ViewChangeManager.html", "d1/db2/classresdb_1_1ViewChangeManager" ],
      [ "ViewChangeTimeout", "d9/d00/classresdb_1_1ViewChangeTimeout.html", "d9/d00/classresdb_1_1ViewChangeTimeout" ]
    ] ]
];