var annotated_dup =
[
    [ "resdb", "d5/d10/namespaceresdb.html", [
      [ "contract", "d8/d28/namespaceresdb_1_1contract.html", [
        [ "AddressManager", "d4/d26/classresdb_1_1contract_1_1AddressManager.html", "d4/d26/classresdb_1_1contract_1_1AddressManager" ],
        [ "ContractClient", "d9/dfa/classresdb_1_1contract_1_1ContractClient.html", "d9/dfa/classresdb_1_1contract_1_1ContractClient" ],
        [ "ContractExecutor", "db/d88/classresdb_1_1contract_1_1ContractExecutor.html", "db/d88/classresdb_1_1contract_1_1ContractExecutor" ],
        [ "ContractManager", "d6/d7d/classresdb_1_1contract_1_1ContractManager.html", "d6/d7d/classresdb_1_1contract_1_1ContractManager" ]
      ] ],
      [ "AsyncAcceptor", "d3/d77/classresdb_1_1AsyncAcceptor.html", "d3/d77/classresdb_1_1AsyncAcceptor" ],
      [ "AsyncReplicaClient", "d8/d9d/classresdb_1_1AsyncReplicaClient.html", "d8/d9d/classresdb_1_1AsyncReplicaClient" ],
      [ "AtomicUniquePtr", "db/d71/classresdb_1_1AtomicUniquePtr.html", "db/d71/classresdb_1_1AtomicUniquePtr" ],
      [ "BatchQueue", "d5/db6/classresdb_1_1BatchQueue.html", "d5/db6/classresdb_1_1BatchQueue" ],
      [ "BlockingQueue", "dd/d88/classresdb_1_1BlockingQueue.html", "dd/d88/classresdb_1_1BlockingQueue" ],
      [ "CheckPointManager", "dc/db0/classresdb_1_1CheckPointManager.html", "dc/db0/classresdb_1_1CheckPointManager" ],
      [ "Commitment", "dd/d4b/classresdb_1_1Commitment.html", "dd/d4b/classresdb_1_1Commitment" ],
      [ "ConsensusService", "d6/d83/classresdb_1_1ConsensusService.html", "d6/d83/classresdb_1_1ConsensusService" ],
      [ "ConsensusServiceGeoPBFT", "de/d17/classresdb_1_1ConsensusServiceGeoPBFT.html", "de/d17/classresdb_1_1ConsensusServiceGeoPBFT" ],
      [ "ConsensusServicePBFT", "d0/dde/classresdb_1_1ConsensusServicePBFT.html", "d0/dde/classresdb_1_1ConsensusServicePBFT" ],
      [ "Context", "d8/d18/structresdb_1_1Context.html", "d8/d18/structresdb_1_1Context" ],
      [ "CrowService", "d1/df3/classresdb_1_1CrowService.html", "d1/df3/classresdb_1_1CrowService" ],
      [ "DataInfo", "dd/dd6/structresdb_1_1DataInfo.html", "dd/dd6/structresdb_1_1DataInfo" ],
      [ "GeoGlobalExecutor", "d4/d2d/classresdb_1_1GeoGlobalExecutor.html", "d4/d2d/classresdb_1_1GeoGlobalExecutor" ],
      [ "GeoPBFTClient", "d5/dcf/classresdb_1_1GeoPBFTClient.html", "d5/dcf/classresdb_1_1GeoPBFTClient" ],
      [ "GeoPBFTCommitment", "df/d2b/classresdb_1_1GeoPBFTCommitment.html", "df/d2b/classresdb_1_1GeoPBFTCommitment" ],
      [ "GeoPBFTExecutorImpl", "dd/d04/classresdb_1_1GeoPBFTExecutorImpl.html", "dd/d04/classresdb_1_1GeoPBFTExecutorImpl" ],
      [ "GeoTransactionExecutor", "d9/d92/classresdb_1_1GeoTransactionExecutor.html", "d9/d92/classresdb_1_1GeoTransactionExecutor" ],
      [ "KeyGenerator", "d5/d5c/classresdb_1_1KeyGenerator.html", null ],
      [ "KVServerExecutor", "d1/de4/classresdb_1_1KVServerExecutor.html", "d1/de4/classresdb_1_1KVServerExecutor" ],
      [ "LockFreeCollectorPool", "d7/d31/classresdb_1_1LockFreeCollectorPool.html", "d7/d31/classresdb_1_1LockFreeCollectorPool" ],
      [ "LockFreeQueue", "da/dd3/classresdb_1_1LockFreeQueue.html", "da/dd3/classresdb_1_1LockFreeQueue" ],
      [ "Logging", "dc/df2/classresdb_1_1Logging.html", "dc/df2/classresdb_1_1Logging" ],
      [ "MockAsyncReplicaClient", "d8/d4f/classresdb_1_1MockAsyncReplicaClient.html", "d8/d4f/classresdb_1_1MockAsyncReplicaClient" ],
      [ "MockCheckPointManager", "de/da4/classresdb_1_1MockCheckPointManager.html", "de/da4/classresdb_1_1MockCheckPointManager" ],
      [ "MockGeoGlobalExecutor", "d7/ddc/classresdb_1_1MockGeoGlobalExecutor.html", "d7/ddc/classresdb_1_1MockGeoGlobalExecutor" ],
      [ "MockResDBClient", "d6/d83/classresdb_1_1MockResDBClient.html", "d6/d83/classresdb_1_1MockResDBClient" ],
      [ "MockResDBReplicaClient", "d6/d79/classresdb_1_1MockResDBReplicaClient.html", "d6/d79/classresdb_1_1MockResDBReplicaClient" ],
      [ "MockResDBService", "d9/d96/classresdb_1_1MockResDBService.html", "d9/d96/classresdb_1_1MockResDBService" ],
      [ "MockResDBTxnClient", "d6/d0e/classresdb_1_1MockResDBTxnClient.html", "d6/d0e/classresdb_1_1MockResDBTxnClient" ],
      [ "MockSignatureVerifier", "de/d05/classresdb_1_1MockSignatureVerifier.html", "de/d05/classresdb_1_1MockSignatureVerifier" ],
      [ "MockSocket", "dd/dd7/classresdb_1_1MockSocket.html", "dd/dd7/classresdb_1_1MockSocket" ],
      [ "MockTransactionExecutorDataImpl", "dc/db6/classresdb_1_1MockTransactionExecutorDataImpl.html", "dc/db6/classresdb_1_1MockTransactionExecutorDataImpl" ],
      [ "MockTransactionExecutorImpl", "d2/dd1/classresdb_1_1MockTransactionExecutorImpl.html", "d2/dd1/classresdb_1_1MockTransactionExecutorImpl" ],
      [ "PerformanceManager", "d1/d89/classresdb_1_1PerformanceManager.html", "d1/d89/classresdb_1_1PerformanceManager" ],
      [ "PrometheusHandler", "df/dcf/classresdb_1_1PrometheusHandler.html", "df/dcf/classresdb_1_1PrometheusHandler" ],
      [ "PYVerificator", "d2/d59/classresdb_1_1PYVerificator.html", "d2/d59/classresdb_1_1PYVerificator" ],
      [ "Query", "de/d6d/classresdb_1_1Query.html", "de/d6d/classresdb_1_1Query" ],
      [ "QueueItem", "df/d64/structresdb_1_1QueueItem.html", "df/d64/structresdb_1_1QueueItem" ],
      [ "RequestInfo", "d8/d15/structresdb_1_1RequestInfo.html", "d8/d15/structresdb_1_1RequestInfo" ],
      [ "ResDBClient", "dd/d87/classresdb_1_1ResDBClient.html", "dd/d87/classresdb_1_1ResDBClient" ],
      [ "ResDBConfig", "db/ddb/classresdb_1_1ResDBConfig.html", "db/ddb/classresdb_1_1ResDBConfig" ],
      [ "ResDBKVClient", "d8/db0/classresdb_1_1ResDBKVClient.html", "d8/db0/classresdb_1_1ResDBKVClient" ],
      [ "ResDBKVPerformanceClient", "de/dd6/classresdb_1_1ResDBKVPerformanceClient.html", "de/dd6/classresdb_1_1ResDBKVPerformanceClient" ],
      [ "ResDBReplicaClient", "d1/d1b/classresdb_1_1ResDBReplicaClient.html", "d1/d1b/classresdb_1_1ResDBReplicaClient" ],
      [ "ResDBServer", "d3/d20/classresdb_1_1ResDBServer.html", "d3/d20/classresdb_1_1ResDBServer" ],
      [ "ResDBService", "d0/d8d/classresdb_1_1ResDBService.html", "d0/d8d/classresdb_1_1ResDBService" ],
      [ "ResDBStateClient", "da/d7c/classresdb_1_1ResDBStateClient.html", "da/d7c/classresdb_1_1ResDBStateClient" ],
      [ "ResDBTest", "dd/d33/classresdb_1_1ResDBTest.html", "dd/d33/classresdb_1_1ResDBTest" ],
      [ "ResDBTestClient", "d8/d65/classresdb_1_1ResDBTestClient.html", "d8/d65/classresdb_1_1ResDBTestClient" ],
      [ "ResDBTestExecutor", "df/d3b/classresdb_1_1ResDBTestExecutor.html", "df/d3b/classresdb_1_1ResDBTestExecutor" ],
      [ "ResDBTxnClient", "d4/daf/classresdb_1_1ResDBTxnClient.html", "d4/daf/classresdb_1_1ResDBTxnClient" ],
      [ "ResDBUserClient", "d3/d9c/classresdb_1_1ResDBUserClient.html", "d3/d9c/classresdb_1_1ResDBUserClient" ],
      [ "ResponseManager", "da/d2f/classresdb_1_1ResponseManager.html", "da/d2f/classresdb_1_1ResponseManager" ],
      [ "SDKTransaction", "df/dbb/structresdb_1_1SDKTransaction.html", "df/dbb/structresdb_1_1SDKTransaction" ],
      [ "ServerFactory", "da/d3b/classresdb_1_1ServerFactory.html", "da/d3b/classresdb_1_1ServerFactory" ],
      [ "SignatureVerifier", "d4/d30/classresdb_1_1SignatureVerifier.html", "d4/d30/classresdb_1_1SignatureVerifier" ],
      [ "Socket", "d0/d29/classresdb_1_1Socket.html", "d0/d29/classresdb_1_1Socket" ],
      [ "SpinLockSet", "d4/d35/classresdb_1_1SpinLockSet.html", "d4/d35/classresdb_1_1SpinLockSet" ],
      [ "Stats", "de/d0d/classresdb_1_1Stats.html", "de/d0d/classresdb_1_1Stats" ],
      [ "SystemInfo", "d9/d27/classresdb_1_1SystemInfo.html", "d9/d27/classresdb_1_1SystemInfo" ],
      [ "TcpSocket", "d4/de5/classresdb_1_1TcpSocket.html", "d4/de5/classresdb_1_1TcpSocket" ],
      [ "TransactionCollector", "d7/d95/classresdb_1_1TransactionCollector.html", "d7/d95/classresdb_1_1TransactionCollector" ],
      [ "TransactionExecutor", "da/dfa/classresdb_1_1TransactionExecutor.html", "da/dfa/classresdb_1_1TransactionExecutor" ],
      [ "TransactionExecutorImpl", "dc/dd6/classresdb_1_1TransactionExecutorImpl.html", "dc/dd6/classresdb_1_1TransactionExecutorImpl" ],
      [ "TransactionManager", "df/d01/classresdb_1_1TransactionManager.html", "df/d01/classresdb_1_1TransactionManager" ],
      [ "TxnMemoryDB", "dd/dd3/classresdb_1_1TxnMemoryDB.html", "dd/dd3/classresdb_1_1TxnMemoryDB" ],
      [ "ViewChangeManager", "d1/db2/classresdb_1_1ViewChangeManager.html", "d1/db2/classresdb_1_1ViewChangeManager" ]
    ] ],
    [ "resdb_validator", "df/dff/namespaceresdb__validator.html", [
      [ "exceptions", "de/ddf/namespaceresdb__validator_1_1exceptions.html", [
        [ "AmountError", "d3/dd4/classresdb__validator_1_1exceptions_1_1AmountError.html", null ],
        [ "AssetIdMismatch", "d1/d5f/classresdb__validator_1_1exceptions_1_1AssetIdMismatch.html", null ],
        [ "ConfigurationError", "dc/d1e/classresdb__validator_1_1exceptions_1_1ConfigurationError.html", null ],
        [ "CyclicBlockchainError", "d9/db4/classresdb__validator_1_1exceptions_1_1CyclicBlockchainError.html", null ],
        [ "DatabaseDoesNotExist", "d3/d20/classresdb__validator_1_1exceptions_1_1DatabaseDoesNotExist.html", null ],
        [ "DoubleSpend", "d5/d3f/classresdb__validator_1_1exceptions_1_1DoubleSpend.html", null ],
        [ "DuplicateTransaction", "d9/dd0/classresdb__validator_1_1exceptions_1_1DuplicateTransaction.html", null ],
        [ "InputDoesNotExist", "d6/dd1/classresdb__validator_1_1exceptions_1_1InputDoesNotExist.html", null ],
        [ "InvalidHash", "d7/db1/classresdb__validator_1_1exceptions_1_1InvalidHash.html", null ],
        [ "InvalidPowerChange", "d7/d9e/classresdb__validator_1_1exceptions_1_1InvalidPowerChange.html", null ],
        [ "InvalidProposer", "dc/d35/classresdb__validator_1_1exceptions_1_1InvalidProposer.html", null ],
        [ "InvalidPublicKey", "db/d2b/classresdb__validator_1_1exceptions_1_1InvalidPublicKey.html", null ],
        [ "InvalidSignature", "d5/d07/classresdb__validator_1_1exceptions_1_1InvalidSignature.html", null ],
        [ "KeypairMismatchException", "d1/de6/classresdb__validator_1_1exceptions_1_1KeypairMismatchException.html", null ],
        [ "MultipleInputsError", "d4/deb/classresdb__validator_1_1exceptions_1_1MultipleInputsError.html", null ],
        [ "MultipleValidatorOperationError", "da/dce/classresdb__validator_1_1exceptions_1_1MultipleValidatorOperationError.html", null ],
        [ "OperationError", "d1/df4/classresdb__validator_1_1exceptions_1_1OperationError.html", null ],
        [ "ResDBError", "df/d1b/classresdb__validator_1_1exceptions_1_1ResDBError.html", null ],
        [ "SchemaValidationError", "d9/dc8/classresdb__validator_1_1exceptions_1_1SchemaValidationError.html", null ],
        [ "StartupError", "de/d19/classresdb__validator_1_1exceptions_1_1StartupError.html", null ],
        [ "ThresholdTooDeep", "db/de1/classresdb__validator_1_1exceptions_1_1ThresholdTooDeep.html", null ],
        [ "TransactionOwnerError", "d8/dc2/classresdb__validator_1_1exceptions_1_1TransactionOwnerError.html", null ],
        [ "UnequalValidatorSet", "d5/d89/classresdb__validator_1_1exceptions_1_1UnequalValidatorSet.html", null ],
        [ "ValidationError", "d7/d5c/classresdb__validator_1_1exceptions_1_1ValidationError.html", null ]
      ] ],
      [ "lib", "dc/d0c/namespaceresdb__validator_1_1lib.html", [
        [ "ResDB", "de/d4d/classresdb__validator_1_1lib_1_1ResDB.html", "de/d4d/classresdb__validator_1_1lib_1_1ResDB" ]
      ] ],
      [ "memoize", "db/ddc/namespaceresdb__validator_1_1memoize.html", [
        [ "HDict", "df/d67/classresdb__validator_1_1memoize_1_1HDict.html", "df/d67/classresdb__validator_1_1memoize_1_1HDict" ],
        [ "ToDictWrapper", "d1/df5/classresdb__validator_1_1memoize_1_1ToDictWrapper.html", "d1/df5/classresdb__validator_1_1memoize_1_1ToDictWrapper" ]
      ] ],
      [ "models", "de/d9a/namespaceresdb__validator_1_1models.html", [
        [ "FastTransaction", "d8/dfa/classresdb__validator_1_1models_1_1FastTransaction.html", "d8/dfa/classresdb__validator_1_1models_1_1FastTransaction" ],
        [ "Transaction", "d9/d68/classresdb__validator_1_1models_1_1Transaction.html", "d9/d68/classresdb__validator_1_1models_1_1Transaction" ]
      ] ],
      [ "transaction", "de/dd1/namespaceresdb__validator_1_1transaction.html", [
        [ "Input", "dc/dbc/classresdb__validator_1_1transaction_1_1Input.html", "dc/dbc/classresdb__validator_1_1transaction_1_1Input" ],
        [ "Output", "d0/da1/classresdb__validator_1_1transaction_1_1Output.html", "d0/da1/classresdb__validator_1_1transaction_1_1Output" ],
        [ "Transaction", "d5/d13/classresdb__validator_1_1transaction_1_1Transaction.html", "d5/d13/classresdb__validator_1_1transaction_1_1Transaction" ],
        [ "TransactionLink", "d1/d5b/classresdb__validator_1_1transaction_1_1TransactionLink.html", "d1/d5b/classresdb__validator_1_1transaction_1_1TransactionLink" ]
      ] ]
    ] ],
    [ "LevelDurable", "de/d3d/classLevelDurable.html", "de/d3d/classLevelDurable" ],
    [ "RocksDurable", "d5/d5b/classRocksDurable.html", "d5/d5b/classRocksDurable" ]
];