version: '3.8'

services:
  crow_server:
    build: .
    command: /bin/bash -c "cd /ResilientDB-GraphQL && bazel-bin/service/http_server/crow_service_main service/tools/config/interface/service.config service/http_server/server_config.config"

  graphql_server:
    build: .
    command: /bin/bash -c "cd /ResilientDB-GraphQL && source venv/bin/activate && gunicorn -b 0.0.0.0:8000 app:app"

  kv_server:
    build: .
    command: /bin/bash -c "cd /resilientdb && ./service/tools/kv/server_tools/start_kv_service.sh"

  nginx:
    image: nginx:latest
    command: nginx -g 'daemon off;' -c /etc/nginx/nginx.conf
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - graphql_server
