var exceptions_8py =
[
    [ "resdb_validator.exceptions.ResDBError", "df/d1b/classresdb__validator_1_1exceptions_1_1ResDBError.html", null ],
    [ "resdb_validator.exceptions.ConfigurationError", "dc/d1e/classresdb__validator_1_1exceptions_1_1ConfigurationError.html", null ],
    [ "resdb_validator.exceptions.DatabaseDoesNotExist", "d3/d20/classresdb__validator_1_1exceptions_1_1DatabaseDoesNotExist.html", null ],
    [ "resdb_validator.exceptions.StartupError", "de/d19/classresdb__validator_1_1exceptions_1_1StartupError.html", null ],
    [ "resdb_validator.exceptions.CyclicBlockchainError", "d9/db4/classresdb__validator_1_1exceptions_1_1CyclicBlockchainError.html", null ],
    [ "resdb_validator.exceptions.KeypairMismatchException", "d1/de6/classresdb__validator_1_1exceptions_1_1KeypairMismatchException.html", null ],
    [ "resdb_validator.exceptions.OperationError", "d1/df4/classresdb__validator_1_1exceptions_1_1OperationError.html", null ],
    [ "resdb_validator.exceptions.ValidationError", "d7/d5c/classresdb__validator_1_1exceptions_1_1ValidationError.html", null ],
    [ "resdb_validator.exceptions.DoubleSpend", "d5/d3f/classresdb__validator_1_1exceptions_1_1DoubleSpend.html", null ],
    [ "resdb_validator.exceptions.InvalidHash", "d7/db1/classresdb__validator_1_1exceptions_1_1InvalidHash.html", null ],
    [ "resdb_validator.exceptions.SchemaValidationError", "d9/dc8/classresdb__validator_1_1exceptions_1_1SchemaValidationError.html", null ],
    [ "resdb_validator.exceptions.InvalidSignature", "d5/d07/classresdb__validator_1_1exceptions_1_1InvalidSignature.html", null ],
    [ "resdb_validator.exceptions.AssetIdMismatch", "d1/d5f/classresdb__validator_1_1exceptions_1_1AssetIdMismatch.html", null ],
    [ "resdb_validator.exceptions.AmountError", "d3/dd4/classresdb__validator_1_1exceptions_1_1AmountError.html", null ],
    [ "resdb_validator.exceptions.InputDoesNotExist", "d6/dd1/classresdb__validator_1_1exceptions_1_1InputDoesNotExist.html", null ],
    [ "resdb_validator.exceptions.TransactionOwnerError", "d8/dc2/classresdb__validator_1_1exceptions_1_1TransactionOwnerError.html", null ],
    [ "resdb_validator.exceptions.DuplicateTransaction", "d9/dd0/classresdb__validator_1_1exceptions_1_1DuplicateTransaction.html", null ],
    [ "resdb_validator.exceptions.ThresholdTooDeep", "db/de1/classresdb__validator_1_1exceptions_1_1ThresholdTooDeep.html", null ],
    [ "resdb_validator.exceptions.MultipleValidatorOperationError", "da/dce/classresdb__validator_1_1exceptions_1_1MultipleValidatorOperationError.html", null ],
    [ "resdb_validator.exceptions.MultipleInputsError", "d4/deb/classresdb__validator_1_1exceptions_1_1MultipleInputsError.html", null ],
    [ "resdb_validator.exceptions.InvalidProposer", "dc/d35/classresdb__validator_1_1exceptions_1_1InvalidProposer.html", null ],
    [ "resdb_validator.exceptions.UnequalValidatorSet", "d5/d89/classresdb__validator_1_1exceptions_1_1UnequalValidatorSet.html", null ],
    [ "resdb_validator.exceptions.InvalidPowerChange", "d7/d9e/classresdb__validator_1_1exceptions_1_1InvalidPowerChange.html", null ],
    [ "resdb_validator.exceptions.InvalidPublicKey", "db/d2b/classresdb__validator_1_1exceptions_1_1InvalidPublicKey.html", null ]
];