package(default_visibility = ["//visibility:public"])

py_binary(
    name = "benchmark_result",
    srcs = ["benchmark_result.py"],
    deps = [
        "//oracle_script/comm:comm_config",
        "//oracle_script/comm:utils",
    ],
)
