cc_binary(
    name = "rocksdb_sample",
    srcs = ["rocksdb_sample.cpp"],
    deps = [
        "//common:comm",
        "//third_party:rocksdb",
    ],
)

cc_binary(
    name = "rocksdb_performance",
    srcs = ["rocksdb_performance.cpp"],
    deps = [
        "//common:comm",
        "//third_party:rocksdb",
    ],
)
