var namespaceresdb__validator_1_1exceptions =
[
    [ "AmountError", "d3/dd4/classresdb__validator_1_1exceptions_1_1AmountError.html", null ],
    [ "AssetIdMismatch", "d1/d5f/classresdb__validator_1_1exceptions_1_1AssetIdMismatch.html", null ],
    [ "ConfigurationError", "dc/d1e/classresdb__validator_1_1exceptions_1_1ConfigurationError.html", null ],
    [ "CyclicBlockchainError", "d9/db4/classresdb__validator_1_1exceptions_1_1CyclicBlockchainError.html", null ],
    [ "DatabaseDoesNotExist", "d3/d20/classresdb__validator_1_1exceptions_1_1DatabaseDoesNotExist.html", null ],
    [ "DoubleSpend", "d5/d3f/classresdb__validator_1_1exceptions_1_1DoubleSpend.html", null ],
    [ "DuplicateTransaction", "d9/dd0/classresdb__validator_1_1exceptions_1_1DuplicateTransaction.html", null ],
    [ "InputDoesNotExist", "d6/dd1/classresdb__validator_1_1exceptions_1_1InputDoesNotExist.html", null ],
    [ "InvalidHash", "d7/db1/classresdb__validator_1_1exceptions_1_1InvalidHash.html", null ],
    [ "InvalidPowerChange", "d7/d9e/classresdb__validator_1_1exceptions_1_1InvalidPowerChange.html", null ],
    [ "InvalidProposer", "dc/d35/classresdb__validator_1_1exceptions_1_1InvalidProposer.html", null ],
    [ "InvalidPublicKey", "db/d2b/classresdb__validator_1_1exceptions_1_1InvalidPublicKey.html", null ],
    [ "InvalidSignature", "d5/d07/classresdb__validator_1_1exceptions_1_1InvalidSignature.html", null ],
    [ "KeypairMismatchException", "d1/de6/classresdb__validator_1_1exceptions_1_1KeypairMismatchException.html", null ],
    [ "MultipleInputsError", "d4/deb/classresdb__validator_1_1exceptions_1_1MultipleInputsError.html", null ],
    [ "MultipleValidatorOperationError", "da/dce/classresdb__validator_1_1exceptions_1_1MultipleValidatorOperationError.html", null ],
    [ "OperationError", "d1/df4/classresdb__validator_1_1exceptions_1_1OperationError.html", null ],
    [ "ResDBError", "df/d1b/classresdb__validator_1_1exceptions_1_1ResDBError.html", null ],
    [ "SchemaValidationError", "d9/dc8/classresdb__validator_1_1exceptions_1_1SchemaValidationError.html", null ],
    [ "StartupError", "de/d19/classresdb__validator_1_1exceptions_1_1StartupError.html", null ],
    [ "ThresholdTooDeep", "db/de1/classresdb__validator_1_1exceptions_1_1ThresholdTooDeep.html", null ],
    [ "TransactionOwnerError", "d8/dc2/classresdb__validator_1_1exceptions_1_1TransactionOwnerError.html", null ],
    [ "UnequalValidatorSet", "d5/d89/classresdb__validator_1_1exceptions_1_1UnequalValidatorSet.html", null ],
    [ "ValidationError", "d7/d5c/classresdb__validator_1_1exceptions_1_1ValidationError.html", null ]
];