package(default_visibility = ["//visibility:public"])

py_binary(
    name = "run_svr",
    srcs = ["run_svr.py"],
    deps = [
        "//oracle_script/comm:comm_config",
        "//oracle_script/comm:utils",
        "//proto:replica_info_py_proto",
    ],
)
