name: Node.js Package Publish

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.20.2'
          registry-url: 'https://registry.npmjs.org/'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project
      - name: Run build
        run: npm run build

      # Publish to npm
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
