package(default_visibility = ["//platform/consensus/ordering:__subpackages__"])

cc_library(
    name = "order_manager",
    srcs = ["order_manager.cpp"],
    hdrs = ["order_manager.h"],
    deps = [
        "//platform/proto:resdb_cc_proto",
    ],
)