cc_library(
    name = "sdk_transaction",
    srcs = ["sdk_transaction.cpp"],
    hdrs = ["sdk_transaction.h"],
)

'''
cc_library(
    name = "pistache_service",
    srcs = ["pistache_service.cpp"],
    hdrs = ["pistache_service.h"],
    deps = [
        ":sdk_transaction",
        "//common:comm",
        "//config:resdb_config_utils",
        "//kv_client:resdb_kv_client",
        "//proto:signature_info_cc_proto",
        "//third_party:pistache",
    ],
)

cc_binary(
    name = "pistache_service_main",
    srcs = ["pistache_service_main.cpp"],
    deps = [
        ":pistache_service",
    ],
)

cc_library(
    name = "crow_service",
    srcs = ["crow_service.cpp"],
    hdrs = ["crow_service.h"],
    deps = [
        ":sdk_transaction",
        "//common:comm",
        "//config:resdb_config_utils",
        "//kv_client:resdb_kv_client",
        "//proto:signature_info_cc_proto",
        "//third_party:crow",
    ],
)

cc_binary(
    name = "crow_service_main",
    srcs = ["crow_service_main.cpp"],
    deps = [
        ":crow_service",
    ],
)
'''
