package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "contract_tools",
    srcs = ["contract_tools.cpp"],
    deps = [
        "//application/contract/client:contract_client",
        "//config:resdb_config_utils",
    ],
)
