package(default_visibility = ["//platform/consensus/ordering/poe:__subpackages__"])

cc_library(
    name = "poe_utils",
    srcs = ["poe_utils.cpp"],
    hdrs = ["poe_utils.h"],
    deps = [
        "//platform/consensus/ordering/poe/proto:poe_cc_proto",
        "//platform/proto:resdb_cc_proto",
    ],
)

cc_library(
    name = "transaction_state",
    hdrs = ["transaction_state.h"],
    deps = [
    ],
)
