package(default_visibility = ["//visibility:public"])

py_library(
    name = "comm_config",
    srcs = ["comm_config.py"],
)

py_library(
    name = "utils",
    srcs = ["utils.py"],
    deps = [
        ":comm_config",
    ],
)
