#cc_binary(
#    name = "crow_example",
#    srcs = ["crow_example.cpp"],
#    deps = [
#        "//third_party:crow",
#    ],
#)

#cc_binary(
#    name = "pistache_example",
#    srcs = ["pistache_example.cpp"],
#    deps = [
#        "//third_party:pistache",
#    ],
#)
