"""
Filename: vector_add.py
Author(s) / Contrubtor(s): Steven Shoemaker / Regan Yang, Ritesh Patro, Yoshiki Yamaguchi, Tiching Kao
Date: 2025-Fall
Description: (Indexers project) Run to save value to ResDB and generate a vector embedding for it
"""

import sys
# TODO: I kept this in here bc it might be a background element that ResDB-orm needs
# but not sure. Delete once everything works
import requests
# TODO: I just copied the entire directory into here, I don't get how this works
# Why do we need to import it from there if it's been globally insalled through pip?
# TODO ^ ditto for config.yaml
from resdb_orm.orm import ResDBORM
import hnsw_library
from leann import LeannBuilder, LeannSearcher
from pathlib import Path
import json
import os
from typing import Dict, Any

WORKING_DIR = Path("./").resolve()

db = ResDBORM()

keylist_key = "ddc7ffb0b82115d79e7c552fbe8fc434d606475375e2b3408eb2fa11ea4deeba"

value_to_add = ''

# TODO: I got this from a guide for parsing system input, but what does it mean? What is the proper
#   way to use it?
# NOTE: It looks like this only runs when you run it as a script and not by linking it in other files
#   as sucnh, you should probably keep all code in here

# TODO: Format these section segmenters better
# - - - - - - - - - SECTION 1: Init and data cleaning - - - - - - - - - >
if __name__ == "__main__":
    # Parse the value that the user is requesting to add
    for i in range (len(sys.argv)):
        # TODO: Consider adding an error message for when users use `--value` with no input
        # TODO: Consider if you need to parse whitespace around `--value`
        # TODO: Consider cases when `--value` isnt a string
        if(sys.argv[i] == '--value'  and (i + 1 != len(sys.argv))):
            value_to_add = sys.argv[i + 1]
            break

        # TODO: Add a --k_num option
    
    if value_to_add == '':
        print("Critical error - the program requires an arguement in the form of `--value stringToSave`")
        # TODO: Make sure that this is the right exit code (this WILL close the whole program)
        exit(1)

# - - - - - - - - - SECTION 2: Retrieve HNSW data or create if it doesnt exist - - - - - - - - - >
    # TODO: Add notes for when you don't have any saved data
    file_embedding_keys = str(WORKING_DIR / "saved_data/embedding_keys.json")
    embedding_keys: Dict[str, Any] = {}
    hnsw_text_entries = [value_to_add]

    # TODO: Look into creating/storing ResDB-orm data with a custom key instead of these autogenerated ones
    #   It might prevent us from having to read keys from an external file
    # TODO: This will fail if the `saved_data` folder does not exist, error handle by first creating the folder if it doesnt
    # If the user has never saved data before, create the file for storing it
    if not os.path.exists(file_embedding_keys):
        embedding_keys = {
            "temp_ids_txt": "",
            "temp_index_txt": "",
            "temp_leann_meta_json": "",
            "temp_leann_passages_txt": "",
            "temp_leann_passages_json": ""
        }
    # If the user does have some form of prior saved data, it should have a list of keys, even if invalid
    else:
        try:
            with open(file_embedding_keys, 'r') as file:
                embedding_keys = json.load(file)
        # TODO: Exit out of execution or error handle here
        except FileNotFoundError:
            print("file not found")
        except json.JSONDecodeError:
            print("File isnt valid json")

    # Ensure that keys for text files are valid. If not, create them
    for field in ["temp_ids_txt", "temp_index_txt", "temp_leann_passages_txt"]:
        key = embedding_keys[field]
        if key is not None and key != "":
            # TODO: Make sure it actually is an Error when you try to get with a key that doesnt work
            try:
                _ = hnsw_library.get_record(key)
            # TODO: Structure this so you don't have the same line of code in two different places
            except:
                embedding_keys[field] = hnsw_library.create_record('')
        else:
            embedding_keys[field] = hnsw_library.create_record('')

    # Ensure that key for this specific json file is valid. If not, create it
    key = embedding_keys["temp_leann_meta_json"]
    if key is not None and key != "":
        # TODO: Make sure it actually is an Error when you try to get with a key that doesnt work
        try:
            print('Getting record')
            _ = hnsw_library.get_record(key)
            print('got the meta json without erorr')
        # TODO: Structure this so you don't have the same line of code in two different places
        except:
            embedding_keys["temp_leann_meta_json"] = hnsw_library.create_record({})
    else:
        embedding_keys["temp_leann_meta_json"] = hnsw_library.create_record({})

    # Ensure that key for this specific json file is valid. If not, create it
    # This file contains the information we need to rebuild the HNSW tree, gather that information
    #   while checking to see if it exists (or use an empty array otherwise)
    key = embedding_keys["temp_leann_passages_json"]
    if key is not None and key != "":
        # TODO: Make sure it actually is an Error when you try to get with a key that doesnt work
        try:
            passages_data = hnsw_library.get_record(key)
            hnsw_text_entries = list(map(lambda dataPoint: dataPoint['text'], passages_data["data"]))
            # TODO: Make sure that this behaves as youd expect
            if value_to_add in hnsw_text_entries:
                print(f"{value_to_add} is already saved as an embedding in the ResDB database")
                sys.exit(0)
            hnsw_text_entries.append(value_to_add)
        # TODO: Structure this so you don't have the same line of code in two different places
        except:
            hnsw_text_entries = [value_to_add]
            embedding_keys["temp_leann_passages_json"] = hnsw_library.create_record([])
    else:
        hnsw_text_entries = [value_to_add]
        embedding_keys["temp_leann_passages_json"] = hnsw_library.create_record([])

    # Open the file in write mode and dump the data
    try:
        with open(file_embedding_keys, 'w') as file:
            json.dump(embedding_keys, file)
        print("Successful write")
    # TODO: Handle this better or error out
    except IOError as e:
        print("IO Error, unsuccessful write: {e}")

# - - - - - - - - - SECTION 3: Construct the HNSW data structure (leann builder) - - - - - - - - - >
    file_temporary_storage = str(WORKING_DIR / "saved_data/temp/temp.leann")

    # TODO: Suppress outputs from leann algorithms, they flood the console

    # TODO: This will fail if the `saved_data/temp` folder does not exist, error handle by first creating the folder 
    #   (after error handling way above to create the saved_data folder) if it doesnt exist
    # If the user has never saved data before, create the file for storing it
    builder = LeannBuilder(backend_name="hnsw")
    for text in hnsw_text_entries:
        builder.add_text(text)
    builder.build_index(file_temporary_storage)

# - - - - - - - - - SECTION 4: Save the new embeddings - - - - - - - - - >
    # Save updated indeces for the text files to ResDB
    for pairing in [
        ("temp.ids.txt", "temp_ids_txt")
        ]:
        
        fileName = str(WORKING_DIR / "saved_data/temp/" / pairing[0])
        key = embedding_keys[pairing[1]]

        try:
            print(fileName)
            # TODO: Change this from rb to just r
            with open(fileName, 'r', encoding='ascii') as file:
                content = file.read()
                hnsw_library.put_record(key, content)
        # TODO: These are critical errors that will break the whole system
        except FileNotFoundError:
            print(f"Error: The file was not found.")
        except Exception as e:
            print(f"An error occurred: {e}")

        # Save updated indeces for the text files to ResDB
    for pairing in [
        ("temp.leann.passages.idx", "temp_leann_passages_txt"),
        ("temp.index", "temp_index_txt")
        ]:
        
        fileName = str(WORKING_DIR / "saved_data/temp/" / pairing[0])
        key = embedding_keys[pairing[1]]

        try:
            print(fileName)
            # TODO: Change this from rb to just r
            with open(fileName, 'r', encoding='Windows-1252') as file:
                content = file.read()
                print(content)
                hnsw_library.put_record(key, content)
        # TODO: These are critical errors that will break the whole system
        except FileNotFoundError:
            print(f"Error: The file was not found.")
        except Exception as e:
            print(f"An error occurred: {e}")



    # Save updated indeces for the json file to ResDB
    fileName = str(WORKING_DIR / "saved_data/temp/" / "temp.leann.meta.json")
    key = embedding_keys["temp_leann_meta_json"]
    try:
        with open(fileName, 'r') as file:
            # TODO: Make sure that this generates JSON content correctly as expected (as a Dict[str, Any])
            content = json.load(file)
            hnsw_library.put_record(key, content)
    # TODO: These are critical errors that will break the whole system
    except FileNotFoundError:
        print(f"Error: The file was not found.")
    except Exception as e:
        print(f"An error occurred: {e}")



    # Save updated indeces for the jsonline (`.jsonl`) files to ResDB
    fileName = str(WORKING_DIR / "saved_data/temp/" / "temp.leann.passages.jsonl")
    key = embedding_keys["temp_leann_passages_json"]
    content = []
    try:
        with open(fileName, 'r') as file:
            for line in file:
                content.append(json.loads(line))
            hnsw_library.put_record(key, content)
    # TODO: These are critical errors that will break the whole system
    except FileNotFoundError:
        print(f"Error: The file was not found.")
    except Exception as e:
        print(f"An error occurred: {e}")


# - - - - - - - - - SECTION 5: Cleanup: Remove temporary files - - - - - - - - - >
    # TODO: Ultimately remove (and at the start of this file, create) the whole temp directory
    # Remove all temporarily created files
    for temp_file_path in ["temp.ids.txt", "temp.index", "temp.leann.passages.idx",
        "temp.leann.meta.json", "temp.leann.passages.jsonl"]:
        fileName = str(WORKING_DIR / "saved_data/temp/" / temp_file_path)

        try:
            os.remove(fileName)
        # TODO: These are non-critical errors, but do this better
        except FileNotFoundError:
            print(f"Error: The file was not found.")
            # TODO: Figure out when this happens (if sudo venv/activate is enough) and warn the user appropriately
        except PermissionError:
            print("Permission error when deleting files in your temp directory")
        except Exception as e:
            print(f"An error occurred: {e}")