package(default_visibility = ["//platform/consensus/ordering:__subpackages__"])

cc_library(
    name = "protocol_base",
    srcs = ["protocol_base.cpp"],
    hdrs = ["protocol_base.h"],
    deps = [
        "//common:comm",
    ],
)

